// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl9GFvYo1M1iq0B4u2ixGO6-QENKILSkY',
    appId: '1:13675564416:web:67beade08f6d0b5f60c565',
    messagingSenderId: '13675564416',
    projectId: 'fittrackerpro-77578',
    authDomain: 'fittrackerpro-77578.firebaseapp.com',
    storageBucket: 'fittrackerpro-77578.firebasestorage.app',
    measurementId: 'G-B5TFM5P9K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ89LbCE7svwt17Li999gyhYwyxyCegog',
    appId: '1:13675564416:android:46845bb2447fedb060c565',
    messagingSenderId: '13675564416',
    projectId: 'fittrackerpro-77578',
    storageBucket: 'fittrackerpro-77578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCza4x5fSOR0BlnOza8yA1GGokADoE8dY',
    appId: '1:13675564416:ios:c25a67fb1c0c055360c565',
    messagingSenderId: '13675564416',
    projectId: 'fittrackerpro-77578',
    storageBucket: 'fittrackerpro-77578.firebasestorage.app',
    iosBundleId: 'com.example.fittrackerpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCza4x5fSOR0BlnOza8yA1GGokADoE8dY',
    appId: '1:13675564416:ios:c25a67fb1c0c055360c565',
    messagingSenderId: '13675564416',
    projectId: 'fittrackerpro-77578',
    storageBucket: 'fittrackerpro-77578.firebasestorage.app',
    iosBundleId: 'com.example.fittrackerpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl9GFvYo1M1iq0B4u2ixGO6-QENKILSkY',
    appId: '1:13675564416:web:5b9363cddd5c1b0060c565',
    messagingSenderId: '13675564416',
    projectId: 'fittrackerpro-77578',
    authDomain: 'fittrackerpro-77578.firebaseapp.com',
    storageBucket: 'fittrackerpro-77578.firebasestorage.app',
    measurementId: 'G-LDE05WFKHK',
  );
}
